language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jalbacristian0493/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jalbacristian0493/react-test npm test

after_success:
  - docker build -t jalbacristian0493/multi-client ./client
  - docker build -t jalbacristian0493/multi-nginx ./nginx
  - docker build -t jalbacristian0493/multi-server ./server
  - docker build -t jalbacristian0493/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jalbacristian0493/multi-client
  - docker push jalbacristian0493/multi-nginx
  - docker push jalbacristian0493/multi-server
  - docker push jalbacristian0493/multi-worker